package study.domain;
// Generated Sep 17, 2016 8:46:39 PM by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;
import org.hibernate.annotations.Parameter;

/**
 * Address generated by hbm2java
 */

@Entity
@FilterDef(name = "ageFilter", parameters = @ParamDef(name = "age", type = "int"))
@Table(name = "address", catalog = "daocuong")
public class Address implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Person> persons = new HashSet<Person>(0);

	public Address() {
	}

	public Address(String name, Set<Person> persons) {
		this.name = name;
		this.persons = persons;
	}

	public Address(String string) {
		// TODO Auto-generated constructor stub
		this.name = string;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	@Filter(name = "ageFilter", condition = "age >  :age")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
