package study.domain;
// Generated Sep 18, 2016 12:38:50 AM by Hibernate Tools 4.3.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.OrderBy;

/**
 * Cat generated by hbm2java
 */
@Entity
@Table(name = "cat", catalog = "daocuong")
public class Cat implements java.io.Serializable {

	private Integer id;
	private Color color;
	private String name;
	private Date birthDay;
	@Column(name="age")
	private Integer age;

	public Cat() {
	}

	public Cat(String name) {
		super();
		this.name = name;
	}

	public Cat(Color color) {
		this.color = color;
	}

	public Cat(Color color, String name, Date birthDay) {
		this.color = color;
		this.name = name;
		this.birthDay = birthDay;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@Cascade({ CascadeType.SAVE_UPDATE })
	@JoinColumn(name = "color_id", nullable = false)
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@PrePersist
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "birth_day", length = 19)
	public Date getBirthDay() {
		return this.birthDay = new Date();
	}

	public void setBirthDay(Date birthDay) {
		this.birthDay = birthDay;
	}

	public Integer getAge() {
		return age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

}
