package study.domain;
// Generated Sep 18, 2016 12:38:50 AM by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name = "color", catalog = "daocuong")
public class Color implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Cat> cats = new HashSet<Cat>(0);

	public Color(String name) {
		super();
		this.name = name;
	}

	public Color() {
	}

	public Color(String name, Set<Cat> cats) {
		this.name = name;
		this.cats = cats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Cat> getCats() {
		return this.cats;
	}

	public void setCats(Set<Cat> cats) {
		this.cats = cats;
	}

}
