package study.domain;
// Generated Sep 17, 2016 6:46:36 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name = "events", catalog = "daocuong")
public class Events implements java.io.Serializable {

	private Integer id;
	private String title;
	private Date dateCreate;
	private Set<Person> persons = new HashSet<Person>(0);

	public Events() {
	}
	

	public Events(String title) {
		super();
		this.title = title;
	}


	public Events(String title, Date dateCreate, Set<Person> persons) {
		this.title = title;
		this.dateCreate = dateCreate;
		this.persons = persons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TITLE", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@PrePersist
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_CREATE", length = 19)
	public Date getDateCreate() {
		return this.dateCreate = new Date();
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@Cascade({CascadeType.ALL})
	@JoinTable(name = "person_event", catalog = "daocuong", joinColumns = {
			@JoinColumn(name = "events_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "person_id", nullable = false, updatable = false) })
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
