package study.domain;
// Generated Sep 17, 2016 8:46:39 PM by Hibernate Tools 4.3.4.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Person generated by hbm2java
 */

@Entity
@Table(name = "person", catalog = "daocuong")
public class Person implements java.io.Serializable {

	private Integer id;
	private Address address;
	private String lastName;
	private String firstName;
	private Integer age;
	private List<Events> eventses = new ArrayList<Events>();

	public Person() {
	}

	public Person(String firstName) {
		super();
		this.firstName = firstName;
	}

	public Person(Address address) {
		this.address = address;
	}

	public Person(Address address, String lastName, String firstName, Integer age, List<Events> eventses) {
		this.address = address;
		this.lastName = lastName;
		this.firstName = firstName;
		this.age = age;
		this.eventses = eventses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@Cascade({ org.hibernate.annotations.CascadeType.SAVE_UPDATE })
	@JoinColumn(name = "address_id", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "lastName", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "firstName", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@Cascade({ org.hibernate.annotations.CascadeType.ALL })
	@JoinTable(name = "person_event", catalog = "daocuong", joinColumns = {
			@JoinColumn(name = "person_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "events_ID", nullable = false, updatable = false) })
	public List<Events> getEventses() {
		return this.eventses;
	}

	public void setEventses(List<Events> eventses) {
		this.eventses = eventses;
	}

}
